### ISSUE TITLE
executable warning from ADMB

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nwfsc-assess/nwfscAgeingError#10]
```
matrix column bound exceeded -- column index 1 is higher than 40 in linad99\fvma_acc.cpp:48.
```
When using the new executable on a simulated data file or the data file in the test folder. The executable runs but does not estimate variance parameters. I was able to use the new executable on the data file that is in the inst\doc folder. I wonder if I the simulated data is wrong?

**Comment by iantaylor-NOAA** [comment]
Thanks for catching this @kellijohnson-NOAA 
I'm assuming that the 4-year-old file https://github.com/nwfsc-assess/nwfscAgeingError/blob/master/examples/Example_with_simulated_data.R just needs to be updated to work with the 3-month-old executable. I don't know what changes AEP made but can help with that at some point in the future.
I see that the example .dat file at https://github.com/nwfsc-assess/nwfscAgeingError/blob/master/inst/doc/agemat.dat does work correctly.
