### ISSUE TITLE
fix GitHub Action to compile Mac and Linux agemat executables 

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nwfsc-assess/nwfscAgeingError#11]
I added a GitHub Action to automatically check this package following the discussion at https://github.com/nwfsc-assess/nwfscSurvey/issues/32.
However, the R-CMD-check badge shows failing status for this package because of the binary ADMB executable file `agemat.exe` in `/inst/executables/`.
I tried two options to work around this:
- "Writing R Extensions" https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-structure says that non-CRAN packages that include binary files can list them in a BinaryFiles file at the top of the package. 
- "R Packages (2nd ed.)" (https://r-pkgs.org/r-cmd-check.html?q=binaryfiles#package-structure) says that "If you’re not submitting to CRAN, you can silence this warning by listing each executable file in the BinaryFiles field in your `DESCRIPTION`."

Neither option worked so I won't waste more time on it.

A better solution would be to remove the executable, have a GitHub Action that installs ADMB, compiles the TPL, and makes platform-specific executables which we could make available as a release at https://github.com/nwfsc-assess/nwfscAgeingError/releases, but I don't feel like working on that now.

**Comment by James-Thorson-NOAA** [comment]
@Cole-Monnahan-NOAA would you have any feedback on this to share given `tmbstan`

**Comment by Cole-Monnahan-NOAA** [comment]
Not sure what you mean by `tmbstan`.. presumably my CI setup on `adnuts`. That's how I did it to start ([link](https://github.com/Cole-Monnahan-NOAA/adnuts/blob/main/.github/workflows/R-CMD-check.yml#L40)), but then it won't run locally. Instead I compile from R during testing ([link](https://github.com/Cole-Monnahan-NOAA/adnuts/blob/main/tests/testthat/setup.R#L4))

The only thing I had to do was add a new PATH entry so it could find the g++ in rtools40. I haven't tested this in other platforms besides WIndows and Ubuntu.

**Comment by iantaylor-NOAA** [comment]
Thanks for the tip, @Cole-Monnahan-NOAA.

In spite of saying I was fed up of working on this low-priority project, I couldn't help but do a little more tinkering. I was able to get the Windows executable previously distributed with the package to build in a GitHub Action as an alternative source of the executable (e.g. https://github.com/nwfsc-assess/nwfscAgeingError/actions/runs/601170844). However, the Linux and Mac builds had "fatal error: admodel.h: No such file or directory", 
https://github.com/nwfsc-assess/nwfscAgeingError/runs/1983882732?check_suite_focus=true#step:6:11
which I presume is because I did something wrong in adding the admb libraries to GITHUB_PATH.

**Comment by Cole-Monnahan-NOAA** [comment]
Try taking out the bin/bash part? Mine worked with just

   - name: Compile model and run
         run: |
         cd tests/simple
         admb simple.tpl

**Comment by iantaylor-NOAA** [comment]
The Windows executable is getting built automatically using GitHub Actions, and can be downloaded from this site via the artifacts from that action, like https://github.com/nwfsc-assess/nwfscAgeingError/suites/2127661138/artifacts/43433436. 

However, I never worked out the "fatal error: admodel.h: No such file or directory" problem for Mac and Linux as discussed above. I believe I tried out the suggestion solution without success but don't have time to dig into it now. 

I just renamed this issue to make it more clear what remains to be done so we can remember to come back to it in the future.

**Comment by James-Thorson-NOAA** [comment]
Its possible that @Cole-Monnahan-NOAA has some insights, I think he used Github Actions for cross-OS testing of `adnuts`.  Cole, any thoughts?

**Comment by Cole-Monnahan-NOAA** [comment]
When I had it working I didn't have this line: 

```` 
echo "/usr/local/bin/admb-12.2/lib" >> $GITHUB_PATH
````

So maybe try deleting that.  I also didn't install this:

````
        yum install -y gcc-c++
````
I'd also try deleting this. This other compiler might be conflicting? 

Otherwise I'd try pinging Johnoel. I ended up compiling with a `system` call from R and I can't remember now why I did that. I think so it worked locally and on GA.

**Comment by iantaylor-NOAA** [comment]
@johnoel, can you help with a `agemat.cpp:7:12: fatal error: 'admodel.h' file not found` error when compiling a simple TPL file for ageing error estimation in this repository?

The Windows compile is working great, but the Mac and Linux (CentOS) workflows 
- Mac: https://github.com/nwfsc-assess/nwfscAgeingError/blob/build-workflows/.github/workflows/build-mac.yml
- CentOS: https://github.com/nwfsc-assess/nwfscAgeingError/blob/build-workflows/.github/workflows/build-centos.yml

are failing with that error as shown in the two actions:
- Mac: https://github.com/nwfsc-assess/nwfscAgeingError/runs/2451619398?check_suite_focus=true#step:4:11
- CentOS: https://github.com/nwfsc-assess/nwfscAgeingError/runs/2451953305?check_suite_focus=true#step:6:11

Those workflows are based on the ones created by @k-doering-NOAA for Stock Synthesis (e.g. 
https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/main/.github/workflows/build-mac.yml), but with the difference that the SS workflow calls a shell script which has the `admb` command within it, which seems unnecessarily complex for this case. If you know of other GitHub workflows that compile ADMB, I'd be happy to see them.

@Cole-Monnahan-NOAA thanks for the suggestions. Taking out `yum install -y gcc-c++` from build-centos.yml caused a failure due to missing g++ and including the admb /lib/ folder in the path made no difference in the results.

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA ,  I have some ideas, although I don't know if any of them will pan out.

I wonder if the cd command is not working properly? maybe instead of https://github.com/nwfsc-assess/nwfscAgeingError/blob/19b44a67b4c2e2efc6ff574b8a8811589e1cd633/.github/workflows/build-mac.yml#L25-L26

try: (EDIT: sorry, should be &&, not &)
```
cd src  && admb agemat 
```

I also think /bin/bash may not be necessary, I think it was needed to run the .sh script... but I could be wrong. 

If that doesn't work, I'm guessing it is something with the compiler like you are thinking. I've seen this error before, but I can't remember under what circumstances. You can try changing the version of mac or centos being used. I'm a little confused b/c the builds for SS are working fine using these versions of mac and centos and the same version of admb.... also instead of the centos docker image, you can try the default ubuntu runner,  this run builds ss with admb using ubuntu-latest: https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/main/.github/workflows/run-no-est.yml

**Comment by iantaylor-NOAA** [comment]
Thanks for the ideas @k-doering-NOAA!
Removing /bin/bash (needed for the script but not the simple call to `admb`) did the trick and now the Mac and Linux executables are now compiling using the pre-compiled ADMB 12.3 downloaded by zip.
