### ISSUE TITLE
Difficulty generating ReadsMat and getting age read matrix in correct format

### ISSUE THREAD

**Issue by gacphillips** [nwfsc-assess/nwfscAgeingError#13]
Hi, not sure where best to ask for help, but I am trying to use the package to generate an ageing error matrix for a reference collection of aged otoliths. I have 7 readers, all otoliths have been read by more than one reader, multiple times, so using a median value for the 'read age'. There are no duplicate rows in the dataset. I have run the help code, but strugging to replicate a dataset with similar format to the 'AgesData2' that is required in RunFn(). It looks like I may also need a ReadsMat file - not sure how to generate this from the data (the user guide is not that clear, for me at least). Is this neccessary for the running of RunFn()?

I think this is the reason I keep getting the following error:

**Warning - there are some missing data; the effective sample size calculation may be dubious
Test Number is not 123456; it is 33
Warning message:
In shell(paste0("agemat.exe", ExtraArgs), intern = Intern) :
  'agemat.exe -est' execution failed with error code 1**

Not sure what it means by missing data - I have already converted any NULL/NA values to -999, and there are no 0 aged fish.

Happy for you to delete this issue and email too if that is easier/more appropriate - Genevieve[dot]Phillips[at]aad[dot]gov[dot]au

**Comment by iantaylor-NOAA** [comment]
@gacphillips sadly debugging this type of error seems difficult.

When the model runs, it produces an `Echo.Out` which shows how the agemat executable is interpreting the inputs provided which may help a bit.

In case it helps I've also just added more information about `Data` argument provided to `RunFn()` in issue #12 (which also has some messy example code showing how the samples with matching combinations of reads are aggregated).

Some of the documentation in this package is out of date (see issue #8), and I'm not sure where you're seeing reference to `AgesData2` or `ReadsMat`. However, the only file you should need to run the estimation is the executable, as the input file (`agemat.dat`) gets written by `RunFn()` (starting on line 211: https://github.com/nwfsc-assess/nwfscAgeingError/blob/master/R/RunFn.R#L211).
