### ISSUE TITLE
fix bug in histograms of readers vs reader plots

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nwfsc-assess/nwfscAgeingError#16]
@andi-stephens-NOAA noticed that the histograms showing the marginal distributions in the reader vs reader plot were misaligned. I think this was due to an indexing issue of 0 vs 1. In commit eb633d20bf5f54814afdebd5b687b1d8bc537980 I went ahead and shifted the distributions so that they are centered on the integer ages to make it more obvious which age is in which bin.
Old (left) vs new (right) is shown below.
![image](https://user-images.githubusercontent.com/4992918/193153892-df9d0db4-38e4-4caa-99b8-ab5cbdd53426.png)

**Comment by andi-stephens-NOAA** [comment]
"Fencepost error" is what this was called in the olden days.
