### ISSUE TITLE
test case steps out of bounds

### ISSUE THREAD

**Issue by jimianelli** [nwfsc-assess/nwfscAgeingError#20]
line 842:
if (AgeA >= 0) Prob2 *= AgeErrOut(Jreader,Age1,AgeA); 
queries give:
(lldb) p Jreader
(int) $0 = 1
(lldb) p Age1
(int) $1 = 1
(lldb) p AgeA
(int) $2 = 41

so maybe AgeA too big?

 3darray AgeErrOut(1,MaxReader,0,MaxAge,0,MaxAge)

MaxAge is 40 on read...

**Comment by jimianelli** [comment]
exasperated in debugging this error, it's in the report section so changed line 842 to

            if (AgeA >= 0&AgeA<=MaxAge) Prob2 *= AgeErrOut(Jreader,Age1,AgeA); 

so program could finish with test data, but unsure this is the best fix (indexing impossible to follow imho)

**Comment by iantaylor-NOAA** [comment]
@jimianelli, I see that the files in the `test` directory do not work with the current release (but do work with the 2013 version of agemat.exe which is still within `test`).

You could instead work with the data and example script for Big Skate that you can find links to here:
https://github.com/pfmc-assessments/nwfscAgeingError/issues/12.

**Comment by iantaylor-NOAA** [comment]
New example files associated with TMB version of the package are working as shown in the vignette: https://pfmc-assessments.github.io/AgeingError/articles/getting_started.html
