### ISSUE TITLE
coordinate requests for 2023 west coast groundfish double read data?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nwfsc-assess/nwfscAgeingError#23]
I'm not sure if this issue belongs here or in PEPtools.

In the past authors of West Coast Groundfish stock assessments have requested double read data by email from Patrick McDonald at NWFSC and from the state agencies. There are some double reads in PacFIN but @kellijohnson-NOAA has said that these are not necessarily complete.

Have folks already requested double read data for 2023 assessments? If not, would it be worth coordinating a request rather than send a bunch of independent emails, or at least listing the points of contact for the age data from each agency?

In the case of Petrale, I think @gertsevv and I would only consider updating the ageing uncertainty matrix for the current ageing method (break and burn) from each lab that has produced new double read ages, which means we would just need info from WDFW and NWFSC (which has aged the samples from Oregon and California as well as the survey samples).

**Comment by brianlangseth-NOAA** [comment]
@iantaylor-NOAA Updated the ageing error matrices is something on our to-do list. We have not yet done so, however we have a number of ages that are still being aged. Most of the new ages are from WDFW or NWFSC (for OR and I think for CA too) and we are also exclusively doing break and burn for this cycle. If you are able to wait until closer to the data deadline (May 1) having a single email to Patrick for Petrale and Canary makes a lot of sense.

**Comment by iantaylor-NOAA** [comment]
Closing this issue as no longer relevant and too specific to NWFSC anyway.
