### ISSUE TITLE
new function added for plots of Reader A vs. Reader B

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nwfsc-assess/nwfscAgeingError#3]
New function [ageing_comparison](https://github.com/nwfsc-assess/nwfscAgeingError/blob/master/R/ageing_comparison.R) just added to this package after finding it in a dusty corner of my hard drive thanks to inquiry from @melmonk. It makes plots like the one below from the raw data that feeds into the ageing error package. Currently the function doesn't include any option to write to PNG file so you have to do that by hand. Also, it could be called form other functions in this package using the same input table (currently it's totally independent).
![ageing comparison 1](https://user-images.githubusercontent.com/4992918/27157149-21f27f40-5115-11e7-85e2-19fbd6905391.png)

**Comment by iantaylor-NOAA** [comment]
This function is now called by `PlotOutputFn` which will create a PNG file like the one posted above in the same directory as the other plots (default is now PNG instead of PDF). Options to modify appearance of this plot, such as `count=TRUE/FALSE` to add the count to each point, can be passed to `PlotOutputFn`.

The `ageing_comparison` function also has some minor changes including a new `png` input if it's called directly, and automatically changing `xaxs='i'` to `xaxs='r'` when there are observations of age 0 fish so the axes won't cut off those points.

**Comment by iantaylor-NOAA** [comment]
Paul Spencer pointed out that the PDF option isn't working due to "ireader" used before it is defined. Shouldn't be too hard to fix. Paul also points out that the README includes out-of-date install instructions.

**Comment by kellijohnson-NOAA** [comment]
Thanks @iantaylor-NOAA for letting me know. Does Paul have a timeline that he needs a fix by?

**Comment by kellijohnson-NOAA** [comment]
fixed Paul's issues with 5757182 @iantaylor-NOAA can we close this issue?

**Comment by iantaylor-NOAA** [comment]
Thanks for doing this, @kellijohnson-NOAA
