### ISSUE TITLE
add more warnings

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nwfsc-assess/nwfscAgeingError#5]
I just made some changes to RunFn in commit b162c4 to warn if the path input as `AdmbFile` doesn't contain the executable to copy into `SaveFile` and to stop the function if the path input as `SaveFile` doesn't contain the executable (whether copied from `AdmbFile` or not). However, other warning messages could be added to help users avoid common errors.

**Comment by kellijohnson-NOAA** [comment]
Closing b/c pertains to ADMB.
